<a href="https://colab.research.google.com/github/AISushilRaj/crosstl/blob/AISushilRaj-Chatbot--1/sushil_CrossGL_crosstl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To clone repository from crosstl

In [ ]:
import git
git.Repo.clone_from("https://github.com/AISushilRaj/crosstl.git", "crosstl")

%cd crosstl

/content/crosstl


In [ ]:
!git checkout -b sushil-crossgl

Switched to a new branch 'sushil-crossgl'


**Project Title: AI-Based Chatbot for Customer Support Automation**

In [80]:
textinput = input("Enter a value: ")

Enter a value: The product is amazing and I absolutely love it! But the delivery service was horrible.


In [81]:
display(textinput)

'The product is amazing and I absolutely love it! But the delivery service was horrible.'

In [82]:
import nltk
import spacy
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk import pos_tag, ne_chunk
from nltk.tree import Tree
from nltk.corpus import wordnet
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec, Doc2Vec
from gensim.models.doc2vec import TaggedDocument

In [83]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [20]:
text = textinput

In [84]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [85]:
sentences = sent_tokenize(text)
words = word_tokenize(text)

In [86]:

print("Sentences:", sentences)
print("Words:", words)

# Stop words removal
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Filtered Words:", filtered_words)


Sentences: ['the delivery service was horrible']
Words: ['the', 'delivery', 'service', 'was', 'horrible']
Filtered Words: ['delivery', 'service', 'horrible']


In [87]:
from nltk import pos_tag
from nltk.tokenize import word_tokenize
nltk.download('averaged_perceptron_tagger_eng')
pos_tags = pos_tag(filtered_words)
print(pos_tags)


[('delivery', 'NN'), ('service', 'NN'), ('horrible', 'NN')]


[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


In [88]:
# Named Entity Recognition (NER)
nltk.download('maxent_ne_chunker_tab')

named_entities = ne_chunk(pos_tags)
print("Named Entities:")
for entity in named_entities:
    if isinstance(entity, Tree):
        print(entity)

# Synonyms and Word Sense Disambiguation
synonyms = set()
for word in filtered_words:
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name())

print("Synonyms:", synonyms)


[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


Named Entities:
Synonyms: {'table_service', 'serving', 'saving', 'service', 'horrible', 'speech', 'frightful', 'deliverance', 'armed_service', 'horrifying', 'servicing', 'service_of_process', 'bringing', 'Robert_William_Service', 'religious_service', 'rescue', 'livery', 'obstetrical_delivery', 'pitch', 'manner_of_speaking', 'divine_service', 'delivery', 'inspection_and_repair', 'avail', 'serve', 'legal_transfer', 'atrocious', 'ugly', 'Service', 'overhaul', 'military_service', 'help'}


In [113]:
# Bag of Words (BoW)
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform([text])
print("\nBag of Words Representation:")
print(X_bow.toarray())
print("Feature Names:", vectorizer.get_feature_names_out())

# TF-IDF
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform([text])
print("\nTF-IDF Representation:")
print(X_tfidf.toarray())
print("Feature Names:", tfidf_vectorizer.get_feature_names_out())



Bag of Words Representation:
[[1 1 1 1 1 1 1 1 1 1 1 2 1]]
Feature Names: ['absolutely' 'amazing' 'and' 'but' 'delivery' 'horrible' 'is' 'it' 'love'
 'product' 'service' 'the' 'was']

TF-IDF Representation:
[[0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.5  0.25]]
Feature Names: ['absolutely' 'amazing' 'and' 'but' 'delivery' 'horrible' 'is' 'it' 'love'
 'product' 'service' 'the' 'was']


In [90]:
from textblob import TextBlob
import pandas as pd

# Assuming 'text' is a list or Series of text data
data = pd.DataFrame(vectorizer.get_feature_names_out())  # Create DataFrame with 'data' column

# Calculate sentiment polarity and add it as a new column
data['sentiment'] = data.apply(lambda text: TextBlob(str(text)).sentiment.polarity)

# Print the DataFrame with the sentiment column
print(data)

          0  sentiment
0  delivery       -1.0
1  horrible        NaN
2   service        NaN
3       the        NaN
4       was        NaN


**...... code starts.......**

In [175]:
negative_response = "Sorry for the bad service. Our customer care will call you back. You can also contact us at +91-100-100."
positive_response ="We are glad you had a great time."

textinput = input("Enter a value: ") #.......................... (USE SUBSCRIBER to get data)
text = textinput

Enter a value: The product is amazing and I absolutely love it! But the delivery service was horrible.


The product is amazing and I absolutely love it! But the delivery service was horrible.

In [176]:
# Bag of Words (BoW)
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform([text])
print("\nBag of Words Representation:")
print(X_bow.toarray())
print("Feature Names:", vectorizer.get_feature_names_out())


def rate_word(word):
   # """Rates a word based on its sentiment polarity."""
    analysis = TextBlob(word)
    polarity = analysis.sentiment.polarity

    if polarity < 0:
        rating = "Negative"  # Bad feeling
    elif polarity > 0:
        rating = "Positive"
    else:
        rating = "Neutral"

    return rating

#vectorizer.get_feature_names_out()
list_of_words = vectorizer.get_feature_names_out()
print(list_of_words)
# Example usage
for word in list_of_words:
    rating = rate_word(word)
    if rating == "Negative":
      print(f"The word '{word}' has a {rating} sentiment.")


Bag of Words Representation:
[[1 1 1 1 1 1 1 1 1 1 1 2 1]]
Feature Names: ['absolutely' 'amazing' 'and' 'but' 'delivery' 'horrible' 'is' 'it' 'love'
 'product' 'service' 'the' 'was']
['absolutely' 'amazing' 'and' 'but' 'delivery' 'horrible' 'is' 'it' 'love'
 'product' 'service' 'the' 'was']
The word 'horrible' has a Negative sentiment.


**now we got only negative words**

the above code is to know what the text is about

**Below code is to give response**

In [177]:
from textblob import TextBlob
import nltk

# Tokenize the text into sentences
nltk.download('punkt')
sentences = nltk.sent_tokenize(text)

# Define a negative sentiment response
negative_response = "Sorry for the bad service. Our customer care will call you back. You can also contact us at +91-100-100."
positive_response ="We are glad you had a great time."


# Track if any negative sentiment is found
negative_found = False

# Analyze sentiment for each sentence
for sentence in sentences:
    blob = TextBlob(sentence)
    sentiment_polarity = blob.sentiment.polarity
    sentiment_label = "Positive" if sentiment_polarity > 0 else "Negative" if sentiment_polarity < 0 else "Neutral"

    print(f"Sentence: {sentence}")
    print(f"Sentiment Polarity: {sentiment_polarity}")
    print(f"Sentiment Label: {sentiment_label}")

    # If any sentence has negative sentiment, set the flag
    if sentiment_label == "Negative":
        negative_found = True
        print(f"Response: {negative_response}")
    print("-" * 50)

# Adjust the overall sentiment label logic
if negative_found:
    overall_label = "Negative"
else:
    overall_blob = TextBlob(text)
    overall_sentiment = overall_blob.sentiment.polarity
    overall_label = "Positive" if overall_sentiment > 0 else "Neutral"

print(f"Overall Sentiment Polarity: {overall_sentiment}")
print(f"Overall Sentiment Label: {overall_label}")

print("......................................")

# Respond based on the presence of negative sentiment
if negative_found:
    print(f"Response: {negative_response}")
else:
    print({positive_response})


Sentence: The product is amazing and I absolutely love it!
Sentiment Polarity: 0.6125
Sentiment Label: Positive
--------------------------------------------------
Sentence: But the delivery service was horrible.
Sentiment Polarity: -1.0
Sentiment Label: Negative
Response: Sorry for the bad service. Our customer care will call you back. You can also contact us at +91-100-100.
--------------------------------------------------
Overall Sentiment Polarity: 0.55
Overall Sentiment Label: Negative
......................................
Response: Sorry for the bad service. Our customer care will call you back. You can also contact us at +91-100-100.


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [178]:
display(text)
if overall_label == "Positive":
    print("\n","The overall sentiment is positive.")
    #....................................(use PUBLISHER )
    print(positive_response)

elif overall_label == "Negative":
    print("\n","The overall sentiment is negative.")
    #....................................(use PUBLISHER )
    print("\n",negative_response)
else:
    print("The overall sentiment is neutral.")




'The product is amazing and I absolutely love it! But the delivery service was horrible.'


 The overall sentiment is negative.

 Sorry for the bad service. Our customer care will call you back. You can also contact us at +91-100-100.


In [173]:
# #!git commit -m "Text Input Handling:"

# "The program accepts user input using input(). The user enters a sentence or paragraph that is analyzed for sentiment."
# "Bag of Words (BoW) Representation:"
# "The text is tokenized into individual words."
# "A Bag of Words model is created using CountVectorizer(), which counts the frequency of each unique word in the text."
# "The resulting matrix (word counts) and feature names (unique words) are displayed."
# "Word Sentiment Rating:"

# "Each word from the Bag of Words feature set is analyzed using the TextBlob library to calculate its sentiment polarity."
# "Based on polarity:"
# "Positive: Polarity > 0"
# "Negative: Polarity < 0"
# "Neutral: Polarity = 0"
# "Words with negative polarity are flagged, and their sentiment is printed."
# "Sentence-Level Sentiment Analysis:"

# "The input text is split into individual sentences."
# "Each sentence is analyzed for sentiment using TextBlob:"
# "Positive: Polarity > 0"
# "Negative: Polarity < 0"
# "Neutral: Polarity = 0"
# "If a sentence has a negative sentiment, a predefined negative response is triggered."
# "Overall Sentiment Analysis:"

# "The overall sentiment polarity is calculated by analyzing the entire input text as a single unit."
# "If any sentence was flagged as negative earlier, the overall sentiment is overridden as Negative. Otherwise, it is determined by the calculated polarity:"
# "Positive: Polarity > 0"
# "Neutral: Polarity = 0"
# "Response Generation:"

# "Based on the overall sentiment:"
# "Positive Sentiment: Displays a predefined positive response."
# "Negative Sentiment: Displays a predefined negative response."
# "Neutral Sentiment: Indicates that the text is neutral."
# "Execution Example:"

# "Input: The product is amazing and I absolutely love it! But the delivery service was horrible."
# "Output:"
# "Sentence 1: Positive (Polarity: 0.6125)"
# "Sentence 2: Negative (Polarity: -1.0)"
# "Overall: Negative (overridden due to the negative sentence)"
# "Response:Sorry for the bad service. Our customer care will call you back"